# Note, removed nvidia related code

services:
  pitt_urc_jetson:
    image: urc_jetson
    container_name: pitt_urc_jetson
    privileged: true
    network_mode: host
    pid: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - ./../../:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rws
      - /dev/cu.usbmodem11201:/dev/cu.usbmodem11201
      # - /dev/bus/usb:/dev/bus/usb
      # - /dev/video0:/dev/video0
      # - /dev/video1:/dev/video1
    restart: unless-stopped
    stdin_open: true
    tty: true
